apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-db
  labels:
    app: catalogue-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: catalogue-db
  template:
    metadata:
      labels:
        name: catalogue-db
    spec:
      containers:
      - name: catalogue-db
        image: gcr.io/project-for-terraform/catalogue-db
        ports: 
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
spec:
  selector:
    app: catalogue-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

        