apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: front-end
        image: gcr.io/project-for-terraform/front-end
        ports: 
        - containerPort: 80
        # livenessProbe:
        #   httpGet: 
        #     path: /
        #     port: 9000  
        #   initialDelaySeconds: 90
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: / 
        #     port: 9000
        #   initialDelaySeconds: 90
        #   periodSeconds: 10
