# apiVersion: v1
# kind: Service
# metadata:
#     name: front-end
# spec:
#     ports:
#         - protocol: TCP    
#           port: 80
#           targetPort: 80
#     selector:
#         name: front-end

kind: Service
apiVersion: v1
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8079
  selector:
    name: front-end
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster

